spring:
  application:
    name: kim-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.0.103:8080/Kim-Itoken/kim-config-profile.git
          search-paths: respo
          username: kim
          password: qw4610125
  boot:
    admin:
      client:
        url: http://localhost:8084

  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/